#!/bin/bash

#CONSTANTS
declare -rx HEADER_EXTENSION="$DREPORT_INCLUDE/gendumpheader"

# @brief Packaging the dump, applying the header
# and transferring to dump location.
function custom_package()
{
    FILE="/tmp/dumpheader_${dump_id}_${EPOCHTIME}"
    compressed_file="$name_dir.bin"
    echo "performing dump compression $name_dir"
    if [ "$dump_type" = "$TYPE_FAULTDATA" ]; then
        rm -rf $name_dir/dreport.log
        rm -rf $name_dir/summary.log
        tar -cf "$compressed_file" -C "$(dirname "$name_dir")" "$(basename "$name_dir")"
    else
        tar cf - -C "$(dirname "$name_dir")" "$(basename "$name_dir")"  | zstd > "$compressed_file"
    fi
    # shellcheck disable=SC2181 # need output from `tar` in above if cond.
    if [ $? -ne 0 ]; then
        echo "$($TIME_STAMP)" "Could not create the compressed tar file"
        rm -r "$compressed_file"
        return "$INTERNAL_FAILURE"
    fi

    echo "Adding Dump Header :"$HEADER_EXTENSION
    ("$HEADER_EXTENSION")

    #Append $compressed_file to $FILE
    cat "$compressed_file" | tee -a "$FILE" > /dev/null
    rm -r "$compressed_file"
    compressed_file = "$FILE"
}

# Executing function
custom_package
