#!/usr/bin/env bash

declare -rx TYPE_FAULTDATA="faultdata"
declare -r PHAL_BACKEND="@PHAL_BACKEND@"

# Function to determine the dump format generation selected for this image
function get_generation() {
    case "$PHAL_BACKEND" in
        legacy)
            printf '%s\n' 'p10'
            ;;
        next)
            printf '%s\n' 'p12'
            ;;
        *)
            echo "Unsupported PHAL backend: $PHAL_BACKEND" >&2
            return 1
            ;;
    esac
}

# @brief fetch serial number
# @param serial number
function fetch_serial_number() {
    serialNo=$(busctl get-property xyz.openbmc_project.Inventory.Manager \
            /xyz/openbmc_project/inventory/system xyz.openbmc_project.Inventory.Decorator.Asset \
        SerialNumber | cut -d " " -f 2 | sed "s/^\(\"\)\(.*\)\1\$/\2/g")

    echo "Fetched SerialNumber : ${serialNo}"
    if [[ -z "$serialNo" || ${#serialNo} -gt 7 || ! $serialNo =~ ^[A-Za-z0-9]+$ ]]; then
        serialNo="0000000"
    else
        # Pad to 7 characters with leading zeros
        serialNo=$(printf "%07s" "$serialNo" | tr ' ' '0')
    fi
}
